In [10]:
# importing all necessary libraries
import numpy as np
import pandas as pd
import random
import time
import math

import multiprocessing
import threading


In [2]:
from google.colab import drive
drive.mount('/content/drive')

from google.colab import files
path = "/content/drive/MyDrive/Monarch/RL/Tic Tac Toe/tpl_250k_variable_penalty.csv"
pmt = pd.read_csv(path)



MessageError: Error: credential propagation was unsuccessful

In [11]:
# Creates an empty board
def create_board():
    return(np.array([[0, 0, 0],
                     [0, 0, 0],
                     [0, 0, 0]]))

# Check for empty places on board
def possibilities(board):
    l = []

    for i in range(len(board)):
        for j in range(len(board)):

            if board[i][j] == 0:
                l.append((i, j))
    return(l)

# Select a random place for the player
def random_place(board, player):
    selection = possibilities(board)
    current_loc = random.choice(selection)
    board[current_loc] = player



    return(board)

#Select the best move using the probability transition matrix after training
def best_move(board, player):

  selections = possibilities(board)
  optimal_move = selections[0]
  optimal_move_score = -99999999

  #optimal_possibilities = selections[0]

  for selection in selections:
    new_board = board.copy()
    new_board[selection] = player

    board_string = numpy_array_to_string(board)
    new_board_string = numpy_array_to_string(new_board)
    if (board_string, new_board_string) not in probability_transition_dict:
      #print("unencountered state")
      probability_transition_dict[(board_string, new_board_string)] = -99999999

    current_move_score = probability_transition_dict[board_string, new_board_string]
    if current_move_score > optimal_move_score:
      optimal_move_score = current_move_score
      optimal_move = selection
    #print(new_board)
    #print(current_move_score)


  #print(optimal_possibilities)
  #optimal_move = random.choice(optimal_possibilities)

  board[optimal_move] = player
  return board


# Checks whether the player has three of their marks in a horizontal row
def row_win(board, player):
    for x in range(len(board)):
        win = True

        for y in range(len(board)):
            if board[x, y] != player:
                win = False
                continue

        if win == True:
            return(win)
    return(win)

# Checks whether the player has three of their marks in a vertical row
def col_win(board, player):
    for x in range(len(board)):
        win = True

        for y in range(len(board)):
            if board[y][x] != player:
                win = False
                continue

        if win == True:
            return(win)
    return(win)

# Checks whether the player has three of their marks in a diagonal row
def diag_win(board, player):
    win = True
    y = 0
    for x in range(len(board)):
        if board[x, x] != player:
            win = False
    if win:
        return win
    win = True
    if win:
        for x in range(len(board)):
            y = len(board) - 1 - x
            if board[x, y] != player:
                win = False
    return win

# Evaluates whether there is a winner or a tie
def evaluate(board, state_list):
    winner = 0

    for player in [1, 2]:
        if (row_win(board, player) or
                col_win(board, player) or
                diag_win(board, player)):
            winner = player
            if len(state_list) > 1:
              update_probability_transition_dictionary(state_list, winner)
    if np.all(board != 0) and winner == 0:
        winner = -1
    return winner

#takes a 2-d numpy array and create a string representation
def numpy_array_to_string(array):
  string_array = ""
  for row in array:
    for element in row:
      string_array += str(element)
  return string_array

#Create transition probability dictionary from imported csv file
# probability_transition_dict = {}
# for i in range(len(pmt)):
#   first_state = pmt.iloc[i, 1][2:11]
#   second_state = pmt.iloc[i, 1][15:24]
#   probability_transition_dict[(first_state, second_state)] = pmt.iloc[i, 2]


# #This will be the highest number in the transition
# probability_transition_dict[first_state, second_state] = pmt.iloc[i, 2]

# #Empty board to first move in the center
# blank_board = numpy_array_to_string(np.zeros((3, 3), dtype=int))
# middle_mid = numpy_array_to_string(np.array([[0, 0, 0], [0, 1, 0], [0, 0, 0]]))

# normalizing_factor = probability_transition_dict[(blank_board, middle_mid)]

# for key in probability_transition_dict.keys():
#   probability_transition_dict[key] = probability_transition_dict[key]/normalizing_factor




In [12]:
# Main function to play the game
def play_game():

    board, winner, counter = create_board(), 0, 1
    print(board)
    state_list = []
    state_list.append(numpy_array_to_string(board))
    # player_number_decision = random.randint(0, 1)
    # if player_number_decision == 0:
    #    player1 = 1
    #    player2 = 2
    # else:
    #    player1 = 2
    #    player2 = 1
    #start = time.time()
    player1 = 1
    player2 = 2
    while winner == 0:
        for player in [player1, player2]:
            board = random_place(board, player)
            state_list.append(numpy_array_to_string(board))
            print("Board after " + str(counter) + " move")
            print(board)
            #sleep(2)
            counter += 1
            if counter > 4:
                winner = evaluate(board, state_list)
            if winner != 0:
                break
    #end = time.time()
    #print("Game over. It took "+ str(end-start) + " seconds")
    return(winner)

# Main function for bot to play with human
def play_game_w_human():
    player_number = int(input("Welcome human to tic tac toe: enter player number (1 or 2) "))

    board, winner, counter = create_board(), 0, 1
    print(board)
    state_list = []
    state_list.append(numpy_array_to_string(board))


    human = 1
    computer = 2
    player_list = [human, computer]
    if player_number == 2:
        human = 2
        computer = 1
        player_list = [computer, human]

    #start = time.time()
    while winner == 0:
        for player in player_list:
          if player == human:
            player_move = input("Enter your next move: ")
            player_move = player_move.split()
            player_move = (int(player_move[0]), int(player_move[1]))
            board[player_move] = player
          else:
            print("best_move_cpu")
            board = best_move(board, player)
            print("Board after " + str(counter) + " move")
            print(board)
          counter += 1
          # if counter > 4:
          winner = evaluate(board, state_list)
          if winner != 0:
            break
    #end = time.time()
    if winner == 1 or winner == 2:
      print("Game over. " + str(winner) + " is the winner")
    else:
      print("The game is a tie!")

    return

In [16]:
#This function is for training (creating a new transition dictionary)
#Change the training parameter to True
penalty_dict = {0:-0.5, 1:-0.75, 2:-0.75, 3:-1, 4:-1, 5:-1.25, 6:-1.25, 7:-1.5, 8:-1.5}
def update_probability_transition_dictionary(state_list, winner, training = True):
    #In case of a tie, do not update anything (might change this later)
    if winner == -1:
      return
    print(state_list)

    if training:
      negative_penalty = -1
      if winner == 1:
        i = 0
        while i <= len(state_list)-1:
          current_state = state_list[i]
          next_state = state_list[i+1]
          penalty_state = -1
          #we need to check index because penalty is on second player
          if i < len(state_list)-2:
            penalty_state = state_list[i+2]
          if (current_state, next_state) not in probability_transition_dict:
            with dict_lock:
              probability_transition_dict[(current_state, next_state)] = 1
          else:
            with dict_lock:
              probability_transition_dict[(current_state, next_state)] += 1
          #print(x,y,probability_transition_dict[(current_state, next_state)])

          if penalty_state != -1:
            if (next_state, penalty_state) not in probability_transition_dict:
              with dict_lock:
                probability_transition_dict[(next_state, penalty_state)] = penalty_dict[i]
              #print(y,z,probability_transition_dict[(next_state, penalty_state)])
            else:
              with dict_lock:
                probability_transition_dict[(next_state, penalty_state)] += penalty_dict[i]
              #print(y,z,probability_transition_dict[(next_state, penalty_state)])
          i += 2
      else:
        i = 1
        while i <= len(state_list)-1:
          current_state = state_list[i]
          next_state = state_list[i+1]
          penalty_state = -1
          #Need to check index because penalty is on first player
          if i > 0:
            penalty_state = state_list[i-1]
          if (current_state, next_state) not in probability_transition_dict:
            with dict_lock:
              probability_transition_dict[(current_state, next_state)] = 1
          else:
            with dict_lock:
              probability_transition_dict[(current_state, next_state)] += 1
          #print(x,y,probability_transition_dict[(x, y)])
          if penalty_state != -1:
            if (penalty_state, current_state) not in probability_transition_dict:
              with dict_lock:
                probability_transition_dict[(penalty_state, current_state)] = penalty_dict[i]
              #print(z,x,probability_transition_dict[(z, x)])
            else:
              with dict_lock:
                probability_transition_dict[(penalty_state, current_state)] += penalty_dict[i]
              #print(z,x,probability_transition_dict[(z, x)])
          i += 2

In [ ]:
# Trial Driver Code

#Launch threads
manager = multiprocessing.Manager()
shared_dict = manager.dict()
dict_lock = threading.Lock()

# probability_transition_dict = {}
import time
n = 100

start = time.time()
# Create a shared dictionary using multiprocessing.Manager()
manager = multiprocessing.Manager()
probability_transition_dict = manager.dict()

# Create a list of threads to modify the dictionary
threads = []
for i in range(50):
    thread = threading.Thread(target=modify_dict, args=(i, i*10))
    threads.append(thread)
    thread.start()

# Wait for all threads to finish
for thread in threads:
    thread.join()


end = time.time()
print("Trials took " + str(end-start) + " seconds")
print(probability_transition_dict)

In [11]:
print(len(probability_transition_dict))
print(probability_transition_dict)


7753
{('000000000', '001000000'): 135.25, ('001000000', '001000200'): 0.5, ('001000200', '011000200'): 0, ('011000200', '011020200'): 0.25, ('011020200', '111020200'): 1, ('000000000', '000010000'): 169.5, ('000010000', '000010020'): -11.0, ('000010020', '100010020'): 6, ('100010020', '100010220'): -3.0, ('100010220', '100010221'): 4, ('010000000', '010020000'): 16.5, ('000000000', '010000000'): 115.25, ('010020010', '012020010'): 0.25, ('010020000', '010020010'): -1, ('012120010', '012122010'): 1, ('012020010', '012120010'): -0.25, ('012122011', '012122211'): 2, ('012122010', '012122011'): -1.5, ('000000000', '100000000'): 112.25, ('100000000', '100020000'): 7.5, ('100020000', '110020000'): -4, ('110020000', '110020200'): 0.25, ('110020200', '111020200'): 2, ('000000000', '000000001'): 134.25, ('000000001', '020000001'): -4.0, ('020000001', '020001001'): 4, ('020001001', '020001201'): -0.5, ('020001201', '020001211'): 1, ('020001211', '220001211'): 0, ('220001211', '221001211'): 3, ('

In [ ]:
#Sanity Checks/Debugging

#Empty board
blank_board = numpy_array_to_string(np.zeros((3, 3), dtype=int))

#first move should always go in the middle
middle_mid = numpy_array_to_string(np.array([[0, 0, 0], [0, 1, 0], [0, 0, 0]]))

#first move to diagonal probabilities should all be within a delta
top_left = numpy_array_to_string(np.array([[1, 0, 0], [0, 0, 0], [0, 0, 0]]))
top_right = numpy_array_to_string(np.array([[0, 0, 1], [0, 0, 0], [0, 0, 0]]))
bottom_left = numpy_array_to_string(np.array([[0, 0, 0], [0, 0, 0], [1, 0, 0]]))
bottom_right = numpy_array_to_string(np.array([[0, 0, 0], [0, 0, 0], [0, 0, 1]]))

#first mode to middle edge probabilities should all be within a delta
top_mid = numpy_array_to_string(np.array([[0, 1, 0], [0, 0, 0], [0, 0, 0]]))
left_mid = numpy_array_to_string(np.array([[0, 0, 0], [1, 0, 0], [0, 0, 0]]))
right_mid = numpy_array_to_string(np.array([[0, 0, 0], [0, 0, 1], [0, 0, 0]]))
bottom_mid = numpy_array_to_string(np.array([[0, 0, 0], [0, 0, 0], [0, 1, 0]]))


In [ ]:
print("middle 1 score: " + str(probability_transition_dict[(blank_board, middle_mid)]))
print("")

print("diagonal move scores")
print("top left: " + str(probability_transition_dict[(blank_board, top_left)]))
print("top right: " + str(probability_transition_dict[(blank_board, top_right)]))
print("bottom left: " + str(probability_transition_dict[(blank_board, bottom_left)]))
print("bottom right: " + str(probability_transition_dict[(blank_board, bottom_right)]))
print("")

print("Middle edge move scores")
print("top mid: " + str(probability_transition_dict[(blank_board, top_mid)]))
print("left mid: " + str(probability_transition_dict[(blank_board, left_mid)]))
print("right mid: " + str(probability_transition_dict[(blank_board, right_mid)]))
print("bottom mid: " + str(probability_transition_dict[(blank_board, bottom_mid)]))

# print("Sample scores from a game played with a human")
# first_state = numpy_array_to_string(np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]]))
# second_state = numpy_array_to_string(np.array([[1, 0, 0], [0, 0, 0], [0, 0, 0]]))
# third_state = numpy_array_to_string(np.array([[1, 0, 0], [0, 2, 0], [0, 0, 0]]))
# fourth_state = numpy_array_to_string(np.array([[1, 0, 1], [0, 2, 0], [0, 0, 0]]))
# fifth_state = numpy_array_to_string(np.array([[1, 2, 1], [0, 2, 0], [0, 0, 0]]))
# sixth_state = numpy_array_to_string(np.array([[1, 2, 1], [1, 2, 0], [0, 0, 0]]))
# seventh_state = numpy_array_to_string(np.array([[1, 2, 1], [1, 2, 0], [0, 2, 0]]))


# print("first score: " + str(probability_transition_dict[(first_state, second_state)]))
# print("second score: " + str(probability_transition_dict[(second_state, third_state)]))
# print("third score: " + str(probability_transition_dict[(third_state, fourth_state)]))
# print("fourth score: " + str(probability_transition_dict[(fourth_state, fifth_state)]))
# print("fifth score: " + str(probability_transition_dict[(fifth_state, sixth_state)]))
# print("sixth score: " + str(probability_transition_dict[(sixth_state, seventh_state)]))



KeyError: ('000000000', '000010000')

In [ ]:
 #run with human input
play_game_w_human()




Welcome human to tic tac toe: enter player number (1 or 2) 1
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Enter your next move: 2 1
best_move_cpu
[[2 0 0]
 [0 0 0]
 [0 1 0]]
-99999999
[[0 2 0]
 [0 0 0]
 [0 1 0]]
-99999999
[[0 0 2]
 [0 0 0]
 [0 1 0]]
-99999999
[[0 0 0]
 [2 0 0]
 [0 1 0]]
-99999999
[[0 0 0]
 [0 2 0]
 [0 1 0]]
-99999999
[[0 0 0]
 [0 0 2]
 [0 1 0]]
-99999999
[[0 0 0]
 [0 0 0]
 [2 1 0]]
-99999999
[[0 0 0]
 [0 0 0]
 [0 1 2]]
1
Board after 2 move
[[0 0 0]
 [0 0 0]
 [0 1 2]]


KeyboardInterrupt: Interrupted by user

In [ ]:
#Experiments to verify the markov reward process works
#Testing agent against random moves, ideally the agent would win 99% of games
#Is the win percentage affected if agent is player 1 or player 2?

#function for agent as player 1
def player1_agent_vs_random_moves():

  board, winner, counter = create_board(), 0, 1
  print(board)
  state_list = []
  state_list.append(numpy_array_to_string(board))

  player1 = 1
  player2 = 2
  while winner == 0:
      for player in [player1, player2]:
        if player == 1:
          board = best_move(board, player)
          state_list.append(numpy_array_to_string(board))
          print("Board after " + str(counter) + " move")
          print(board)
          counter += 1

        if player == 2:
          board = random_place(board, player)
          state_list.append(numpy_array_to_string(board))
          print("Board after " + str(counter) + " move")
          print(board)
          counter += 1

        if counter > 4:
            winner = evaluate(board, state_list)
        if winner != 0:
            break
  return(winner)

#function for agent as player 2
def random_moves_vs_agent_player_2():

  board, winner, counter = create_board(), 0, 1
  print(board)
  state_list = []
  state_list.append(numpy_array_to_string(board))

  player1 = 1
  player2 = 2
  while winner == 0:
      for player in [player1, player2]:
        if player == 1:
          board = random_place(board, player)
          state_list.append(numpy_array_to_string(board))
          print("Board after " + str(counter) + " move")
          print(board)
          counter += 1

        if player == 2:
          board = best_move(board, player)
          state_list.append(numpy_array_to_string(board))
          print("Board after " + str(counter) + " move")
          print(board)
          counter += 1

        if counter > 4:
            winner = evaluate(board, state_list)
        if winner != 0:
            break
  return(winner)

#This will be deterministic until delta move function is finished
def agent_vs_agent():
  board, winner, counter = create_board(), 0, 1
  print(board)
  state_list = []
  state_list.append(numpy_array_to_string(board))

  player1 = 1
  player2 = 2
  while winner == 0:
      for player in [player1, player2]:
        if player == 1:
          board = best_move(board, player)
          state_list.append(numpy_array_to_string(board))
          print("Board after " + str(counter) + " move")
          print(board)
          counter += 1
        if player == 2:
          board = best_move(board, player)
          state_list.append(numpy_array_to_string(board))
          print("Board after " + str(counter) + " move")
          print(board)
          counter += 1
        if counter > 4:
            winner = evaluate(board, state_list)
        if winner != 0:
            break
  return(winner)




In [ ]:
n = 100000
start_player_1_agent = time.time()
counter_player_1_agent = 0
lose_list_player_1_agent = []
tie_list_player_1_agent = []
for i in range(n):

  winner = player1_agent_vs_random_moves()
  if winner == 1:
    counter_player_1_agent += 1
  elif winner == 2:
    lose_list_player_1_agent.append(i)
  else:
    tie_list_player_1_agent.append(i)
  print(i)
end_player_1_agent = time.time()



start_player_2_agent = time.time()
counter_player_2_agent = 0
lose_list_player_2_agent = []
tie_list_player_2_agent = []
for i in range(n):
  winner = random_moves_vs_agent_player_2()
  if winner == 2:
    counter_player_2_agent += 1
  elif winner == 2:
    lose_list_player_2_agent.append(i)
  else:
    tie_list_player_2_agent.append(i)
  print(i)
end_player_2_agent = time.time()

print("Trials took " + str(end_player_1_agent-start_player_1_agent) + " seconds")
print(str(counter_player_1_agent) + " wins out of " + str(n) + " trials")

print("win percentage: ", (counter_player_1_agent/n)*100,"%")
print("tie percentage: ", (len(tie_list_player_1_agent)/n)*100,"%")
print("lose percentage: ", (len(lose_list_player_1_agent)/n)*100,"%")
print("")
print("")
print("")
print("Trials took " + str(end_player_2_agent-start_player_2_agent) + " seconds")
print(str(counter_player_2_agent) + " wins out of " + str(n) + " trials")

print("win percentage: ", (counter_player_2_agent/n)*100,"%")
print("tie percentage: ", (len(tie_list_player_2_agent)/n)*100,"%")
print("lose percentage: ", (len(lose_list_player_2_agent)/n)*100,"%")



Streaming output truncated to the last 5000 lines.
[[1 2 2]
 [0 1 1]
 [0 0 0]]
Board after 6 move
[[1 2 2]
 [2 1 1]
 [0 0 0]]
Board after 7 move
[[1 2 2]
 [2 1 1]
 [0 0 1]]
['000000000', '100000000', '120000000', '120001000', '122001000', '122011000', '122211000', '122211001']
99846
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[1 0 0]
 [0 0 0]
 [0 0 0]]
Board after 2 move
[[1 2 0]
 [0 0 0]
 [0 0 0]]
Board after 3 move
[[1 2 0]
 [0 0 0]
 [0 0 1]]
Board after 4 move
[[1 2 2]
 [0 0 0]
 [0 0 1]]
Board after 5 move
[[1 2 2]
 [0 0 0]
 [0 1 1]]
Board after 6 move
[[1 2 2]
 [2 0 0]
 [0 1 1]]
Board after 7 move
[[1 2 2]
 [2 0 1]
 [0 1 1]]
Board after 8 move
[[1 2 2]
 [2 2 1]
 [0 1 1]]
Board after 9 move
[[1 2 2]
 [2 2 1]
 [1 1 1]]
['000000000', '100000000', '120000000', '120000001', '122000001', '122000011', '122200011', '122201011', '122221011', '122221111']
99847
[[0 0 0]
 [0 0 0]
 [0 0 0]]
Board after 1 move
[[0 0 0]
 [0 0 0]
 [0 1 0]]
Board after 2 move
[[2 0 0]
 [0 0 0]
 [0 1 0]]
Board 

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>